### ISSUE TITLE
Colleague changes

### ISSUE THREAD

**Issue by JorisGoosen** [flathub/org.jaspstats.JASP#11]
@bilelmoussaoui would you mind making the following changes to this repo-permissions:

Removing  @amirmasoudabdol  from those who have access.

Adding @RensDofferhoff as contributor.

Many thanks!

**Comment by TingPing** [comment]
[amirmasoudabdol](https://github.com/amirmasoudabdol) never had access.

I've invited [RensDofferhoff](https://github.com/RensDofferhoff)

**Comment by JorisGoosen** [comment]
Thank you!

**Comment by RensDofferhoff** [comment]
Thanks!
