### ISSUE TITLE
Another colleague needs access

### ISSUE THREAD

**Issue by JorisGoosen** [flathub/org.jaspstats.JASP#4]
@bilelmoussaoui would you mind adding @amirmasoudabdol as contributor here a la https://github.com/flathub/org.jaspstats.JASP/issues/2 ?

**Comment by bilelmoussaoui** [comment]
Invitation sent

**Comment by JorisGoosen** [comment]
Merci!

**Comment by amirmasoudabdol** [comment]
Thanks!
